### ISSUE TITLE
Worker name is "Nameless Worker" on uplexa.online even when it is set

### ISSUE THREAD

**Issue by lokety** [uPlexa/upx-android-miner#10]
I have set a worker name and it shows up on top of the home screen but it shows up as "Nameless Worker" on https://uplexa.online/workers.html.

**Comment by QuantumLeaper** [comment]
Hey @lokety,
For uplexa.online you'll need to add an "@" before your worker name

**Comment by lokety** [comment]
> Hey @lokety,
> For uplexa.online you'll need to add an "@" before your worker name

Yes this works. Closing issue.
