### ISSUE TITLE
Home screen not updated and app crashes after app is in background and then brought to foreground

### ISSUE THREAD

**Issue by lokety** [uPlexa/upx-android-miner#11]
Steps

1. Start mining.
2. Push app in background.
3. Switch back to app.

Home screen stops updating and is blank i.e. as if it hasn't started mining. After a few more seconds, app crashes.

**Comment by n3alz** [comment]
I am unable to reproduce this issue. Which device  are you using?

**Comment by ghost** [comment]
also with my phone it does the same problem, App enters the background, then I go to reopen it but afterwards it crashes!

**Comment by lokety** [comment]
> I am unable to reproduce this issue. Which device are you using?

This was on the OnePlus 7T but not lately. I suspect this and some others have been related to flaky pool connection.
I'll close this for the moment.
