### ISSUE TITLE
XLA Copyright

### ISSUE THREAD

**Issue by QuantumLeaper** [uPlexa/upx-android-miner#13]
I, among others, surely share the same anger and frustration that another project, XLA, had - at one point, forked the uPlexa android miner repository, stripped our copyright, and advertised our android miner as their own. However, as much as I dislike the actions taken by one or more of their contributors, I am going to assume it was not that of the entire XLA contributor base.

It is clear that @n3alz has taken some code from XLA, and implemented it in our android miner code repository - which is fine, and it looks great. However, let's not make the same mistake as they once did. Please add the copyrights where necessary @n3alz 

Thank you

**Comment by Mas7erMind** [comment]
Do you have proof of what you say? Can you show us what code we forked? The code that some community member forked in 2018/2019 was inspired by https://github.com/Mine2Gether/m2g_android_miner, https://github.com/ElijaxApps-org/android-xmrig-miner and https://github.com/bobbieltd/semiMiner, not yours. By the way, I am pretty sure you guys also forked Mine2gether to work on your first app, but obviously didn't credit them either...

**Comment by hayzamjs** [comment]
Just in case you were not aware, the miner version that you seem to be talking about wasn’t made by a contributor of the main project, it was just some community member we cannot take responsibility for what people can do, but we didn’t endorse the app that he/she uploaded to play store and considering all this, when we asked the person who was responsible for the community version of the miner, he was clear that he didn’t use UPX software.

**Comment by Mas7erMind** [comment]
> It is clear that @n3alz has taken some code from XLA

"some" code? Are you serious? He copied all of it and just changed the logo.

**Comment by QuantumLeaper** [comment]
> Do you have proof of what you say? Can you show us what code we forked? The code that some community member forked in 2018/2019 was inspired by https://github.com/Mine2Gether/m2g_android_miner and https://github.com/bobbieltd/semiMiner, not yours. By the way, I am pretty sure you guys also forked Mine2gether to work on your first app, but obviously didn't credit them either...

Hmm, so we forked mine2gether before they even created a repository on Github? We all know Scala contribs will not take responsibility for their actions nor the past, but now making up even further ridiculous and idiotic accusations?

**Comment by Mas7erMind** [comment]
I said "I'm pretty sure", if it's not the case then my bad. Actually we should not have to ask what project you forked, as it should be indicated everywhere in your code and Readme... Looks more like it comes from https://github.com/bobbieltd/semiMiner.

And talking about idiotic accusations, what about this one?

> at one point, forked the uPlexa android miner repository, stripped our copyright, and advertised our android miner as their own

Have you read what we wrote just a few posts above? Where is the proof of your accusation?

> Please add the copyrights where necessary @n3alz

Also, it's not only "please", it's "do it ASAP if you don't want to have DMCA on your back".

**Comment by QuantumLeaper** [comment]
> I said "I'm pretty sure", if it's not the case then my bad. Actually we should not have to ask what project you forked, as it should be indicated everywhere in your code and Readme... Looks more like it comes from https://github.com/bobbieltd/semiMiner.
> 
> And talking about idiotic accusations, what about this one?
> 
> > at one point, forked the uPlexa android miner repository, stripped our copyright, and advertised our android miner as their own
> 
> Have you read what we wrote just a few posts above? Where is the proof of your accusation?
> 
> > Please add the copyrights where necessary @n3alz
> 
> Also, it's not only "please", it's "do it ASAP if you don't want to have DMCA on your back".

No, "Please" is good enough. Thank you.

Yout community has already proven that one or more of your contributors stole our code.

**Comment by Mas7erMind** [comment]
Proof?

**Comment by QuantumLeaper** [comment]
> Proof?

You deleted the repositories, but if I want to waste some time today I will dig it up on the internet archive ❤

@n3alz do whatever you wish brothern, I am staying out of this one

**Comment by Mas7erMind** [comment]
> do whatever you wish brothern, I am staying out of this one

Unfortunately for you, you don't have a choice: https://tldrlegal.com/license/gnu-general-public-license-v3-%28gpl-3%29

The fact that you make it "optional" tells a lot about your project.

**Comment by n3alz** [comment]
Issue resolved.
Thanks ladies.
