### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by fwp25** [uPlexa/upx-android-miner#15]
![Screenshot_2021-02-18-03-46-06-426_com miui bugreport](https://user-images.githubusercontent.com/67990245/108259460-1240b700-719c-11eb-813c-84aef0a8c007.jpg)
 this bug from my androis phone

![Screenshot_2021-02-18-03-45-20-141_com uplexa androidminer](https://user-images.githubusercontent.com/67990245/108259524-27b5e100-719c-11eb-9810-1d130e654e24.jpg)
![Screenshot_2021-02-18-03-48-56-647_com uplexa androidminer](https://user-images.githubusercontent.com/67990245/108259609-41572880-719c-11eb-8b04-4b8ef8e07922.jpg)

Custom pool start with DNS error

where the blackscreen button, i love to use that.
thank you

**Comment by n3alz** [comment]
Hello. Please reference one issue per issue.

Duplicate issue as #12
